### ISSUE TITLE
saving images on network volume

### ISSUE THREAD

**Issue by john-mnz** [davefojtik/RunPod-Fooocus-API#1]
Hi @davefojtik
I have deployed a serverless endpoint based on your code and I have noticed that the generated Images get saved on the network volume.
what would happen if the network volume gets filled?
is there a way to prevent the images from being saved there?
I only use the base64 images that the API returns and don't need them to be saved anywhere

thanks again for your help

**Comment by davefojtik** [comment]
@john-mnz Currently I could not find such settings either in the original `lllyasviel/Fooocus`, nor in `konieshadow/Fooocus-API`. And in the end it makes sense. Even the API is made so that, for example, it can return url links to the files themselves, so in order to serve images purely from memory, developers would have to rewrite this part of Fooocus a bit.

We cannot prevent the saving itself, but there is still a solution to the storage part. I updated the [start.sh](https://github.com/davefojtik/RunPod-Fooocus-API/blob/main/src/start.sh) file with a simple rm command that clears the outputs folder on each run. I tested it and this way you'll always have just the latest image saved on the network volume. Hope you'll find this workaround sufficient.

**Comment by john-mnz** [comment]
@davefojtik Yes I looked for that setting too and couldn't find anything.
reading your point I agree now that it makes sense.

I upgraded my endpoint with the solution you provided and it worked perfectly.
thanks for your quick response and detailed explanations.
you're the best
