### ISSUE TITLE
require_base64 not working with async request

### ISSUE THREAD

**Issue by dancingbannana** [davefojtik/RunPod-Fooocus-API#10]
When async_process is true and require_base64 is also true, the resulting webhook does not contain the base64 bytes.

**Comment by davefojtik** [comment]
Hello. I believe that's a correct [Fooocus-API](https://github.com/konieshadow/Fooocus-API) behaviour. But can I ask why are you using async_process? It's more of a static host feature. The RunPod serverless enpoints are already async and scalable with their own queue.

**Comment by dancingbannana** [comment]
I have a different serverless function that calls this where I do some additional processing to the image afterwards. I was trying to see if I could shortcut creating a docker image myself.

**Comment by davefojtik** [comment]
I would need to know more about what you're trying to achieve. But in general, three main possible ways of getting the image from this type of endpoint are:
- Requiring base64 and sending the request to the RUNSYNC
- Requiring base64, sending the request to the RUN (async) and checking the status of that RunPod job with your app, retrieving the output base64 as it changes to "COMPLETED"
- Customizing handler code and adding your own logic at the end to send the output somewhere (POST base64, upload the image file to some external server etc.)

Or if you have some other app on RunPod, they can share the same network volume and you can access the outputs directly. Otherwise we treat the endpoints as "compute only" and I don't recommend calling them only to serve the images from history. That's not very effective.

**Comment by dancingbannana** [comment]
Thanks for this. Here is a bit more info if people want to implement this. I ended up doing kicking off the request with ```https://api.runpod.ai/v2/{podid}/run``` making sure to set ```webhook_url``` on the data object (this will return an id used later: ```id```). The trick is to add a parameter or path to the url to create a unique id for it. ex: ```"https://mywebservice/doneProcessing?id=" + uniqueId```. Now when the request is done, you can look up the request with that ```uniqueId``` from the url and call ```https://api.runpod.ai/v2/{podid}/status/{id}```. This will contain the base64. Note: occasionally it will return a status of still processing but in that case, I just try again some seconds later.
