### ISSUE TITLE
get image of an ongoing async run 

### ISSUE THREAD

**Issue by CyrusVorwald** [davefojtik/RunPod-Fooocus-API#11]
I have an async RunPod call that I get the image of when the RunPod job is COMPLETED. However, I am trying to figure out how to get the image of a running process, similar to https://github.com/mrhan1993/Fooocus-API/issues/51. This means, in addition to the RunPod call being async, the Fooocus API call also needs to be async.

Let's say I have the following:
- RunPod endpoint at https://api.runpod.ai/v2/abcd1234
- Call run at https://api.runpod.ai/v2/abcd1234/run
- I receive back a completed RunPod job ID that looks like this:
{
    "delayTime": 1350,
    "executionTime": 50,
    "id": "7a857de9-e180-4226-be6b-1a1585c597cd-u1",
    "output": {
        "job_id": "3d653995-23ea-4311-bfee-dec98d8fca8c",
        "job_progress": 0,
        "job_result": null,
        "job_stage": "WAITING",
        "job_status": null,
        "job_step_preview": null,
        "job_type": "Text to Image"
    },
    "status": "COMPLETED"
}

But I am not sure what to do with the Fooocus job id, 3d653995-23ea-4311-bfee-dec98d8fca8c, or what the HTTP request to the Fooocus API would be in this case.

**Comment by davefojtik** [comment]
Normally, you would take the job id and send it to the `query-job` endpoint with `"require_step_preview": "true"`. While this endpoint is technically covered, calling it from your app won't do much on RunPod Serverless. Because of how requests work there, it spins another instance/waits in a queue where no such job exists. That's why we can't stream the previews as you would normally do.

I admit that we don't serve previews on Discord and nobody requested it here yet. So I didn't implement an alternative for it. But since you just did, let's make it happen.

I added this piece of code to the [handler.py](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/src/handler.py)
```python
...
# Main process
json = run_inference(event["input"])

if 'preview_url' in event["input"] and 'job_step_preview' in json:
        try:
            job_finished = False
            while job_finished is False:
                preview = sd_session.get('http://127.0.0.1:8888/v1/generation/query-job', params={"job_id":json["job_id"], "require_step_preview": "true"}).json()
                requests.post(event["input"]["preview_url"], json=preview, headers=event["input"].get('preview_headers', ''))
                if(preview["job_stage"] == "SUCCESS" or preview["job_stage"] == "ERROR"):
                    job_finished = True
                    return
                time.sleep(event["input"].get('preview_interval', 1))
        except Exception as e:
            print("async preview task failed: ", e)
            return e
```
With this, you'll be able to use an additional `preview_url` param in your payload that specifies your app's listening endpoint for the incoming POST requests. Also optional `preview_interval` and `preview_headers` where you can specify how often it should update and request headers to be sent (e.g. for auth tokens etc.)

---
**Update:** It's tested and working on RunPod. Feel free to experiment with it by using `3wad/runpod-fooocus-api:0.3.30-standalone_dev2` on the endpoint. (_Make sure to turn the number of active workers to 0 and back to your typical number to force the image change_)

The new payload params should look like this:
```json
{
    "input":{
        "api_name":"txt2img",
        "prompt":"sample prompt",
        "require_base64": true,
        "async_process": true,

        "preview_url": "https://your-app-url/endpoint",
        "preview_interval":1,
        "preview_headers": {
           "Cookie": "foo=bar"
        }
    }
}
```

I'll merge it to main when you confirm the solution is suitable and we'll close the issue.

**Comment by davefojtik** [comment]
**Update:** It's tested and working on RunPod. Feel free to experiment with it by using `3wad/runpod-fooocus-api:0.3.30-standalone_dev2` on the endpoint. (_Make sure to turn the number of active workers to 0 and back to your typical number to force the image change_)

The new params in payload should look like this:
```json
"preview_url": "https://your-app-url/endpoint",
"preview_interval":1,
"preview_headers": {
    "Cookie": "foo=bar"
}
```

I'll merge it to main after a while or when you confirm it's ok like this.

**Comment by CyrusVorwald** [comment]
Thanks! Will take a look when I get a chance

**Comment by davefojtik** [comment]
Previews feature merged with the new update. Closing this issue as completed. Thanks for your feedback!
