### ISSUE TITLE
Question: Is this optimized for production use?

### ISSUE THREAD

**Issue by TowhidKashem** [davefojtik/RunPod-Fooocus-API#18]
Hi,

Thank you for making this! I need to run Fooocus api on a serverless rudpod endpoint for an app I'm building so this seems like exactly what I need. I have never deployed anything that required GPU resources before so excuse my ignorance but I had a few questions:

* Is this api stable? 
* Is it optimized for production use:
  * So far I have used Fooocus with the UI (on runpod) but for the api we don't need one, so does this version not load the UI at all or is it still loaded just not used? I'm guessing the api version can be optimized by ditching the UI completely right?
* Does this also handle the offline GPT based prompt expansions that the UI version of Fooocus does on all prompts to improve them with additional context before sending them to stable diffusion?
* Is this api based on https://github.com/mrhan1993/Fooocus-API? if so how is it different, like what was done to make it compatible with runpod serverless?

Thank you!

**Comment by davefojtik** [comment]
Hello. 

- This repo is indeed a RunPod implementation of https://github.com/mrhan1993/Fooocus-API. On installation, it directly pulls specific commits of code from Fooocus-API and the official Fooocus GitHub. To make it compatible with runpod serverless, we had to write [handler.py](https://github.com/davefojtik/RunPod-Fooocus-API/blob/NetworkVolume/src/handler.py) which takes your RunPod JSON request and internally waits for Fooocus-API response. You can see that it also includes a couple of custom functionalities that were needed to make certain Fooocus features work on such a platform, like accepting and managing input images from both base64 and URLs, transforming JSON to multipart/form-data request or async preview sending. And of course, Dockerfiles and scripts to make it all work either as [Standalone](https://github.com/davefojtik/RunPod-Fooocus-API/tree/Standalone) stateless worker or the one connected to a [Network volume](https://github.com/davefojtik/RunPod-Fooocus-API/tree/NetworkVolume)
- The GPT2 prompt expansion works just fine. It's activated by choosing "Fooocus V2" in the `style_selections` param
- This repo is known to be used in several production projects, including a paid cloud image generation service or as a tool for our own AI agent. The Fooocus-API uses the FastAPI interface. The original Gradio WebUI is disabled.
- While both the Fooocus-API and this repo can and did contain some bugs in the past as any code ever, they're all active projects and we're quickly fixing all issues. Plus this repo is not always automatically on the latest version of Fooocus-API. We're updating the compatibility only after we see that the release is stable, working and tested for a while.

Hope this answers the questions. Feel free to ask more!

**Comment by TowhidKashem** [comment]
> Hello.
> 
> * This repo is indeed a RunPod implementation of https://github.com/mrhan1993/Fooocus-API. On installation, it directly pulls specific commits of code from Fooocus-API and the official Fooocus GitHub. To make it compatible with runpod serverless, we had to write [handler.py](https://github.com/davefojtik/RunPod-Fooocus-API/blob/NetworkVolume/src/handler.py) which takes your RunPod JSON request and internally waits for Fooocus-API response. You can see that it also includes a couple of custom functionalities that were needed to make certain Fooocus features work on such a platform, like accepting and managing input images from both base64 and URLs, transforming JSON to multipart/form-data request or async preview sending. And of course, Dockerfiles and scripts to make it all work either as [Standalone](https://github.com/davefojtik/RunPod-Fooocus-API/tree/Standalone) stateless worker or the one connected to a [Network volume](https://github.com/davefojtik/RunPod-Fooocus-API/tree/NetworkVolume)
> * The GPT2 prompt expansion works just fine. It's activated by choosing "Fooocus V2" in the `style_selections` param
> * This repo is known to be used in several production projects, including a paid cloud image generation service or as a tool for our own AI agent. The Fooocus-API uses the FastAPI interface. The original Gradio WebUI is disabled.
> * While both the Fooocus-API and this repo can and did contain some bugs in the past as any code ever, they're all active projects and we're quickly fixing all issues. Plus this repo is not always automatically on the latest version of Fooocus-API. We're updating the compatibility only after we see that the release is stable, working and tested for a while.
> 
> Hope this answers the questions. Feel free to ask more!

Thanks for the really clear answers Dave, really appreciate it! 🙏  I'm feeling really good about going with the project then, and since you offered I did have a couple more n00b questions if you don't mind 😬:

* Do I need to worry about scaling if I user this on Runpod? Runpod is supposed to auto scale right? Is Fooocus and especially these api versions of Fooocus able to handle lots of concurrent users?
  * Is it right that when a serverless endpoint is invoked every user gets their own "instance" of it, if so then that means the same container/resources/etc aren't shared among users no matter how many there are and this design/approach horizontally scales right?

* I heard the api that comes with the Fooocus UI which uses Gradio has a queueing system by default. Does this lib use any queuing systems where each user is put in a line of some sort and a request can't start until the previous ones end? Or is this api able to handle concurrent requests simultaneously no matter how many requests are happening at a time? 

* I'm guessing you're not downloading the base sdxl model and the checkpoints and loras every single time a request is made by a user to the serverless endpoint right? Because it seems that would be too resource intensive and slow to be practical. If I understand correctly that's what the `Network Volume` branch is for, so you only need to do that once and after that it will read from the disk, is that right? If so, then does this mean the `Standalone` version does in fact download all these things for every serverless request?

* When I use Runpod for the Fooocus UI I usually destroy my pod after since they charge some small fee to keep your files around. For the `Volume` version of the api I'm guessing there's some kind of fee to keep it around right? If so, could you give me an idea of how much that is per month?

* I think Runpod is supposed to be cheaper than Replicate, but could you maybe compare how much hosting a serverless endpoint of this api on Runpod will be compared to say using the base api which already has an endpoint on Replicate?:

https://replicate.com/konieshadow/fooocus-api?output=json

According to the note at the bottom: `This model costs approximately $0.030 to run on Replicate`. So approximately 3 cents USD per run. Obviously the downside to using that one is you can't customize it much but I just wonder how much using Replicate is compared to Runpod for this sort of endpoint..

----

Thanks again, you've been really helpful. I'll try to implement the lib later tonight, can't wait!

**Comment by davefojtik** [comment]
- The GPUs and these workloads for them are not much "concurrent" when speaking about a single machine. While batch jobs do exist, typically you generate images with one job after another. Especially when you take into account that each job can require different models, loras or settings loaded.
- Scaling and queuing are approached a bit differently here. Normally when you have one machine with Fooocus on it, you need the build-in queue so the new jobs can wait and automatically start when the current one finishes.
‎ 
On RunPod serverless, you have many machines (workers) available and waiting in a cluster, so when one is performing a job already, another one can immediately and concurrently execute another one coming in. And if all of them are busy, it will simply wait similarly to the build-in queue. This is why we're actually not using the build-in, instead, we rely on the RunPods one.
‎ 
There you can also set things like the maximum amount of workers (limited by the amount of funds you have on your RunPod account), how long they stay up after the job finishes (so if there is another job available they don't have to shut down and boot up between them) or the amount of waiting time or requests that are needed to give the job to another worker.
- Even though the workers are running a Docker image, and you can connect to them while they're running from the dashboard, you don't typically think about them in a pod way, that "users will be on them", or about "instances". Think about them more as "stateless compute endpoints" that just accept HTTP requests, execute something and return the result. The individual workers don't know about each other, and the RunPod doesn't even know about the Fooocus jobs running on them. Just the returned results. That's why the `jobqueue` endpoint doesn't do anything here for example. Because the runpod doesn't know which worker's inner Fooocus state you want to check, and instead tries to send that request to a non-busy worker that would return an empty Fooocus queue. That's one of the things we had to rewrite as you asked. Preview streaming and a couple of other things work differently in our implementation to overcome this.
- Because the serverless workers are stateless, that's where the Network volume comes in. If you want to e.g. save the output images or let users upload their models, loras etc. you can use it. But it comes with a price - Each Network volume is charged $0.07/GB/Month and when the Fooocus is installed there, the jobs take longer because it has to load the models and files over the network instead of the worker's local disk.
‎ 
And that's also the difference between the [NetworkVolume](https://github.com/davefojtik/RunPod-Fooocus-API/tree/NetworkVolume) and [Standalone](https://github.com/davefojtik/RunPod-Fooocus-API/tree/Standalone) version. The network volume is installed there and loads to workers over the network. The Standalone version, on the other hand, has all the files and models baked into the Docker image itself. So neither of them needs to download anything when they run. Because the Standalone loads everything from a fast local SSD, the jobs are executed much faster. So if you want the most cost-effective solution, I would suggest using that. The downside of the Standalone is that if you want to change the contents of the image, you have to rebuild, reupload and redeploy it each time.
- The price per image depends on the job type, but to give you an idea: a simple txt2img job using a Standalone version executes anywhere between ~7s when cached with [Flashboot](https://blog.runpod.io/introducing-flashboot-1-second-serverless-cold-start/), to ~18s in uncached cold start on RTX4090. That GPU being priced at $0.00044/s gives you about $0,003 to $0,008 per image.

**Comment by TowhidKashem** [comment]
> * The GPUs and these workloads for them are not much "concurrent" when speaking about a single machine. While batch jobs do exist, typically you generate images with one job after another. Especially when you take into account that each job can require different models, loras or settings loaded.
> * Scaling and queuing are approached a bit differently here. Normally when you have one machine with Fooocus on it, you need the build-in queue so the new jobs can wait and automatically start when the current one finishes.
>   ‎
>   On RunPod serverless, you have many machines (workers) available and waiting in a cluster, so when one is performing a job already, another one can immediately and concurrently execute another one coming in. And if all of them are busy, it will simply wait similarly to the build-in queue. This is why we're actually not using the build-in, instead, we rely on the RunPods one.

Ah that's right, I guess in a normal setup the queue does make sense and in the serverless setup it's not applicable due to the fundamental differences in how they work.

>   There you can also set things like the maximum amount of workers (limited by the amount of funds you have on your RunPod account), how long they stay up after the job finishes (so if there is another job available they don't have to shut down and boot up between them) or the amount of waiting time or requests that are needed to give the job to another worker.

True, I guess if I start to see any bottlenecks I can improve performance by adding more workers, keeping some warm at all times, etc.

> * Even though the workers are running a Docker image, and you can connect to them while they're running from the dashboard, you don't typically think about them in a pod way, that "users will be on them", or about "instances". Think about them more as "stateless compute endpoints" that just accept HTTP requests, execute something and return the result. The individual workers don't know about each other, and the RunPod doesn't even know about the Fooocus jobs running on them. Just the returned results. That's why the `jobqueue` endpoint doesn't do anything here for example. Because the runpod doesn't know which worker's inner Fooocus state you want to check, and instead tries to send that request to a non-busy worker that would return an empty Fooocus queue. That's one of the things we had to rewrite as you asked. Preview streaming and a couple of other things work differently in our implementation to overcome this.

Makes sense!

> * Because the serverless workers are stateless, that's where the Network volume comes in. If you want to e.g. save the output images or let users upload their models, loras etc. you can use it. But it comes with a price - Each Network volume is charged $0.07/GB/Month and when the Fooocus is installed there, the jobs take longer because it has to load the models and files over the network instead of the worker's local disk.
>   ‎
>   And that's also the difference between the [NetworkVolume](https://github.com/davefojtik/RunPod-Fooocus-API/tree/NetworkVolume) and [Standalone](https://github.com/davefojtik/RunPod-Fooocus-API/tree/Standalone) version. The network volume is installed there and loads to workers over the network. The Standalone version, on the other hand, has all the files and models baked into the Docker image itself. So neither of them needs to download anything when they run. Because the Standalone loads everything from a fast local SSD, the jobs are executed much faster. So if you want the most cost-effective solution, I would suggest using that. The downside of the Standalone is that if you want to change the contents of the image, you have to rebuild, reupload and redeploy it each time.

Ah got it! I totally forgot that on docker everything is "packaged up" once the image is built. For some reason I was thinking that each time the serverless endpoint booted up it would need to go and fetch all the models and other resources but as you mentioned in the standalone version all that is already available in the serverless function's code base and thus can be accessed locally from it's own ssd.

My app is targeting pretty casual users so definitely don't need to enable them to upload their own models or loras or anything and I only need to return the images back in the response so no need to save it disk long term so I guess the standalone version is the right one for my use case then!

I will most likely need to fork the package so I can use my own model/lora instead of the default ones. And customize the settings a bit. Maybe a feature suggestion for the future could be a config file that lets you define your own urls for model, loras, etc or just a Fooocus compatible config file that can be used to overwrite the ones in the package so there won't be a need to fork.. 🤔

> * The price per image depends on the job type, but to give you an idea: a simple txt2img job using a Standalone version executes anywhere between ~7s when cached with [Flashboot](https://blog.runpod.io/introducing-flashboot-1-second-serverless-cold-start/), to ~18s in uncached cold start on RTX4090. That GPU being priced at $0.00044/s gives you about $0,003 to $0,008 per image.

Ah that's good to know, so 0.3 to 0.8/1 cents vs 3 cents on replicate per image. I guess runpod is the winner then!

----

Thanks again for all the info, you've been really helpful!!

**Comment by davefojtik** [comment]
To create your own image, download the Standalone source code, open the [Dockerfile](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/Dockerfile), and there you can specify your own contents. Can be both local files or use wget for links. The first two are the default model and lora, the rest are required controlnet models for all endpoints. Then you can change default settings in [/src/default.json](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/src/default.json). Defaults are used when you don't specify the models and loras in the request payload like this:
```json
{
   "input": {
      "api_name":"txt2img",
      "prompt":"your-prompt",
      "base_model_name": "yourmodel.safetensors",
      "loras": [
         {
            "enabled": true,
            "model_name": "yourlora.safetensors",
            "weight": 0.8
         }
      ],
      "require_base64": true
   }
}
```
After that, cd into the folder with Dockerfile and run `docker build .`, `docker tag dockerhubname/containername:version` and `docker push dockerhubname/containername:version` (you can upload them into a private repo, just add your hub credentials to RunPod in account settings), then you can use your own image on the serverless endpoint instead of our prebuilt one.

I am glad I could help. Good luck with the app. Feel free to share your achievements with it, or ask for more help in case of any issues.

**Comment by TowhidKashem** [comment]
> To create your own image, download the Standalone source code, open the [Dockerfile](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/Dockerfile), and there you can specify your own contents. Can be both local files or use wget for links. The first two are the default model and lora, the rest are required controlnet models for all endpoints. Then you can change default settings in [/src/default.json](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/src/default.json). Defaults are used when you don't specify the models and loras in the request payload like this:
> 
> ```json
> {
>    "input": {
>       "api_name":"txt2img",
>       "prompt":"your-prompt",
>       "base_model_name": "yourmodel.safetensors",
>       "loras": [
>          {
>             "enabled": true,
>             "model_name": "yourlora.safetensors",
>             "weight": 0.8
>          }
>       ],
>       "require_base64": true
>    }
> }
> ```
> 
> After that, cd into the folder with Dockerfile and run `docker build .`, `docker tag dockerhubname/containername:version` and `docker push dockerhubname/containername:version` (you can upload them into a private repo, just add your hub credentials to RunPod in account settings), then you can use your own image on the serverless endpoint instead of our prebuilt one.
> 
> I am glad I could help. Good luck with the app. Feel free to share your achievements with it, or ask for more help in case of any issues.

Ah perfect, it's my first time working with docker so the baby steps are much appreciated 🙏 and I was able to get the default image working in runpods as a serverless endpoint. Going to try the customized version next!
