### ISSUE TITLE
speed issue on runpod 4090

### ISSUE THREAD

**Issue by john-mnz** [davefojtik/RunPod-Fooocus-API#2]
Hi again @davefojtik

I had the feeling for a while that my serverless endpoint in Runpod is slower than it should be on a 4090, so yesterday I did some testing.

I deployed a normal pod using this repo https://github.com/ashleykleynhans/fooocus-docker on a RTX4090 and I was getting on average 7.2 it/s

but in my serverless endpoint using this repo I only get 3.9 it/s on average

do you have any idea what might be the cause?
since we could get a huge speed boost hence cost reduction if we were running at that speed

**Comment by davefojtik** [comment]
Hi @john-mnz 

Well, it's quite hard to compare these two 1:1. 
- Runpod Serverless endpoints and GPU Cloud pods can run on different nodes and cluster setups. We don't know how they manage resource allocation and how they're shared.
- The individual data centres and workers can vary in speed too based on their hardware, load and optimization. The fact that my serverless workers run 4.5+ it/s now quite confirms this statement. So benchmarking anything on such a dynamic cluster won't give us very precise and reproducible data.
- The software itself has major differences. One is using "clean" Fooocus, on serverless we have to use Fooocus-API. There are differences in requirements, default settings and even which ones are available.
- To at least partially rule out the influence of the above points you would have to benchmark the same version of `konieshadow/Fooocus-API` on the pod with the one wrapped in serverless.

But instead of comparing apples to oranges I would probably _fooocus_ (heh) on trying to continuously optimize what we use. This may include experimenting with the following:
- RunPod FlashBoot
- Foocus-API base and advanced_params that you generate with
- Different version of models ([Juggernaut v7](https://civitai.com/models/133005/juggernaut-xl?modelVersionId=240840) is out and the author is already working on v8)
- In new versions of Fooocus and Fooocus-API we can use additional CMD flags that can drastically affect performance (mainly cuda-allocation, float precisions, attentions and vram settings), see [Fooocus: All CMD Flags](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags) and [Fooocus-API: CMD Flags](https://github.com/konieshadow/Fooocus-API?tab=readme-ov-file#cmd-flags)
- Or perhaps Konie or lllyasviel could certainly know more about speed optimization of their software than I do.

Please let me know if any of this helps you speed up the generation. Unfortunately, I currently don't have time to optimize mine as I'm working on a lot of other projects. Good luck!

**Comment by john-mnz** [comment]
thanks for your insights @davefojtik
I will look into it and let you know if I made any significant progress

thanks again for your quick response

**Comment by john-mnz** [comment]
Hi @davefojtik

I managed to get the speed boost
first, I tried running konieshadow/Fooocus-API on a pod and it also gave me around 7 it/s so I knew there was something wrong with our wrapped version
after testing sooo many things I figured the problem is we are using an old pytorch version since the code for generativelabs tutorial was some 7 month old.

the short answer to fixing this for me was to simply change the first (actually second if you consider the comment) line of the Dockerfile to this: 

FROM runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel-ubuntu22.04

I hope it helps you too

**Comment by davefojtik** [comment]
Ahh. Good catch! I was so busy writing the rest of my discord bot code that I neglected the most basic thing.
It really almost doubled the speed, thanks!

I updated it with the rest of today's code maintenance to support new version features. I am glad you're sharing the knowledge here. More heads know more. Have a nice new year! 🎉

**Comment by john-mnz** [comment]
happy to help

I hope things go great with your bot and happy new year🎉
