### ISSUE TITLE
Possible to create 3wad/runpod-fooocus-api:0.3.29 standalone?

### ISSUE THREAD

**Issue by aleph65** [davefojtik/RunPod-Fooocus-API#29]
Hey, back in February I was using 0.29 version with network volume and had some concurrency issues when I ran 30x jobs at once with the Network Volume (jobs would fail; if I ran 5x at once they would fail less); once I upgraded to the Standalone in version 0.30 everything went perfectly

However there were some things in v0.29 which worked well for me (some nuances in image quality)

Is there any chance you could build an image for 0.3.29 Standalone, like you have the ones today? :)

Happy to help here as well - once again, thanks for your amazing work!

**Comment by davefojtik** [comment]
That would require me to basically do a big update but backwards. Many things from today's versions weren't supported back then. And since they were mainly bug fixes and performance improvements, I would rather suggest using the latest version and customising it to match the generation quality you are used to. 

The main difference between the current images and `<=0.3.30` is the default model (_Juggernaut **V6** vs **V8**_). By following the [standalone guide](https://github.com/davefojtik/RunPod-Fooocus-API/blob/Standalone/docs/standalone-guide.md) you'll be able to make an image with whatever model you want. The rest that affect the results are "just" params and prompts. This way you'll have the latest performance, functionalities and your favourite model.
> V6 model link: https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors

Or if this is not what you meant by the "_nuances in image quality_", please describe the differences more.

**Comment by aleph65** [comment]
thanks so much! that's exactly it

I will check the guide to see how to use Juggernautv6

Thanks again!
